#!/bin/sh
#
# @name flifo v1 Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Marco Ruggia <marco.ruggia@fhgr.ch>
#

# global settings
set VEHICLE_TYPE flifo 				# start rc.flifo_apps (modules needed by flifo)
param set SYS_AUTOCONFIG    1 		# override parameters on boot (except calib & rc param)
param set SDLOG_PROFILE     1049 	# high data rate logging
param set COM_KILL_DISARM   0 		# immediately disarm when kill switch is engaged
param set FD_FAIL_R         0 		# disable roll failsafe (for flip)
param set FD_FAIL_P         0 		# disable pitch failsafe (for flip)

# sensors
param set IMU_GYRO_RATEMAX  800 	# 800hz gyro rate for multicopters
param set EKF2_IMU_POS_Z    0.016 	# imu is 16mm below cog
param set EKF2_EV_CTRL      11 		# fuse 3d position + yaw from mocap
param set EKF2_EV_DELAY     6 		# estimate of mocap delay [ms]
param set EKF2_EVA_NOISE    0.002 	# mocap angle noise
param set EKF2_EVP_NOISE    0.0005  # mocap position noise
param set EKF2_EV_NOISE_MD  1 		# use above noise parameters
param set EKF2_HGT_REF      3       # use mocap for altitude reference
param set EKF2_BARO_CTRL    0 		# don't fuse barometer to altitude (mocap is better)
param set EKF2_MAG_TYPE     5 		# don't fuse magnetormeter data (mocap is better)
param set EKF2_MAG_CHECK    0 		# disable magnetometer ekf2 checks
param set COM_ARM_MAG_ANG   -1 		# disable magnetometer arming checks
param set SYS_HAS_MAG       0 		# ignore magnetometers in qgc

# mavlink
param set MAV_SYS_ID        1 		# mavlink id: 1
param set MAV_TYPE          2 		# mavlink type: quadcopter
param set MAV_1_CONFIG      301 	# mavlink enable over wifi
param set MAV_1_MODE        0 		# mavlink normal mode (ammount of messages)
param set MAV_1_FORWARD     0 		# mavlink disable message forwarding
param set MAV_1_RADIO_CTL   0 		# mavlink disable radio dependent throttling
param set MAV_1_RATE        82944 	# mavlink 82944b/s data rate (90% of max)
param set SER_WIFI_BAUD     921600 	# mavlink wifi baud rate

# flight modes
param set COM_FLTMODE1      8 		# altitude (up)
param set COM_FLTMODE4      2 		# position (middle)
param set COM_FLTMODE6      3 		# mission (down)

# power
param set BAT1_SOURCE       2 		# get battery info from esc's
param set BAT1_N_CELLS      4 		# 4S battery
param set BAT1_V_CHARGED    4.1 	# 4.1V full cell voltage (under load)
param set BAT1_V_EMPTY      3.3 	# 3.3V empty cell voltage (under load)

# esc's (must be reversible)
param set CA_R_REV          255 	# all motors are reversible
param set PWM_MAIN_TIM0     -2 		# DSHOT1200
param set DSHOT_3D_ENABLE   1 		# 3D mode
param set DSHOT_MIN         0.0 	# no minimum throttle
param set DSHOT_3D_DEAD_L   1000 	# no low deadband
param set DSHOT_3D_DEAD_H   1000 	# no high deadband
param set DSHOT_TEL_CFG     101 	# DSHOT telemetry port = TELEM1
param set MOT_POLE_COUNT    14 		# motors pole count

# actuators
param set CA_AIRFRAME       11 		# flifo airframe
param set CA_ROTOR_COUNT    8 		# 8 rotors (1-4: when right-side-up, 5-8: when up-side-down)
param set PWM_MAIN_FUNC1    104 	# pwm 1 = rotor 4 & 8
param set PWM_MAIN_FUNC2    102 	# pwm 2 = rotor 2 & 6
param set PWM_MAIN_FUNC3    101 	# pwm 3 = rotor 1 & 5
param set PWM_MAIN_FUNC4    103 	# pwm 4 = rotor 3 & 7

# general control parameters
param set MC_AT_EN          1 		# enable autotune
param set MC_AIRMODE        2 		# allow throttle to be increased/decreaset to maintain attitude control
param set SYS_VEHICLE_RESP  0.8 	# vehicle responsiveness to stick inputs (maximal)
param set MPC_MANTHR_MIN    0 		# no minimum throttle required, since air-mode
param set MPC_THR_MIN       0.05 	# no minimum throttle required, since air-mode (cant set 0 exactly)
param set HTE_THR_RANGE     0.10 	# expected hover throttle range (maximal)
param set MPC_THR_HOVER     0.38 	# hover throttle (right-side-up) (HQProp 3D 5x3.5x3)
param set FLIFO_THR_CORR    0.80 	# up-side-down hover correction factor independent of geometry or props
param set FLIFO_THR_MIN     0.20 	# minimum throttle to avoid arms oscillating

# rate control (desired 1 Nm for given 1 rad/s error)
param set MC_YAWRATE_K      1.00 	# right-side-up K gain
param set MC_PITCHRATE_K    0.80 	#
param set MC_ROLLRATE_K     0.80 	#
param set MC_YAWRATE_P      0.03 	# right-side-up P gain
param set MC_PITCHRATE_P    0.12 	#
param set MC_ROLLRATE_P     0.12 	#
param set MC_YAWRATE_I      0.04 	# right-side-up I gain
param set MC_PITCHRATE_I    0.18 	#
param set MC_ROLLRATE_I     0.18 	#
param set MC_YAWRATE_D      0.000 	# right-side-up D gain
param set MC_PITCHRATE_D    0.003 	#
param set MC_ROLLRATE_D     0.003 	#
param set MC_YAWRATE_MAX    360.0 	# rate limits
param set MC_PITCHRATE_MAX  7200.0 	#
param set MC_ROLLRATE_MAX   7200.0 	#

# attitude control (desired 1 rad/s for given 1 rad error)
param set MC_YAW_P          6.50
param set MC_PITCH_P        6.50
param set MC_ROLL_P         6.50

# position control
param set MPC_XY_VEL_P_ACC  3.00
param set MPC_Z_VEL_P_ACC   8.00
param set MPC_XY_VEL_I_ACC  0.40
param set MPC_Z_VEL_I_ACC   2.00
param set MPC_XY_VEL_D_ACC  0.20
param set MPC_Z_VEL_D_ACC   0.00
param set MPC_XY_P          2.00
param set MPC_Z_P           3.00

# flifo control
param set FLIFO_USD_YR_K    0.90 	# up-side-down rate K gain (PID same as in right-side-up)
param set FLIFO_USD_PR_K    1.00 	# 
param set FLIFO_USD_RR_K    0.80 	# 
param set FLIFO_ROT_YR_K    0.00 	# transition rate K gain (on top of previous K*PID)
param set FLIFO_ROT_PR_K    0.00 	# 
param set FLIFO_ROT_RR_K    0.50 	# 

# flifo transition parameters
param set FLIFO_SPK_TME     0.15 	# duration of throttle spike before transition [s]
param set FLIFO_SPK_THR1    1.30 	# factor of hover throttle spike before flip RSU->USD
param set FLIFO_SPK_THR2    1.50 	# factor of hover throttle spike before flip USD->RSU
param set FLIFO_ROT_TME     0.40 	# duration of flip transition [s]
param set FLIFO_ROT_THR     1.00 	# factor of hover throttle during transition
param set FLIFO_ROT_X_ACC   0.18 	# percentage of flip transition spent accelerating
param set FLIFO_ROT_X_DEC   0.60 	# percentage of flip transition spent decellerating
param set FLIFO_ROT_T_ACC1  0.60 	# feedforward flip torque when accelerating RSU->USD
param set FLIFO_ROT_T_ACC2  0.50 	# feedforward flip torque when accelerating USD->RSU
param set FLIFO_ROT_T_DEC1  1.50 	# feedforward flip torque when decellerating RSU->USD
param set FLIFO_ROT_T_DEC2  1.40 	# feedforward flip torque when decellerating USD->RSU

# maximum motor slew rate
param set CA_R0_SLEW 0.008
param set CA_R1_SLEW 0.008
param set CA_R2_SLEW 0.008
param set CA_R3_SLEW 0.008
param set CA_R4_SLEW 0.008
param set CA_R5_SLEW 0.008
param set CA_R6_SLEW 0.008
param set CA_R7_SLEW 0.008

# propeller characteristics (right-side-up) (HQProp 3D 5x3.5x3)
param set CA_ROTOR0_CT +13.10
param set CA_ROTOR1_CT +13.10
param set CA_ROTOR2_CT +13.10
param set CA_ROTOR3_CT +13.10
param set CA_ROTOR0_KM -0.013
param set CA_ROTOR1_KM -0.013
param set CA_ROTOR2_KM +0.013
param set CA_ROTOR3_KM +0.013
# propeller characteristics (up-side-down) (HQProp 3D 5x3.5x3)
param set CA_ROTOR4_CT +12.50
param set CA_ROTOR5_CT +12.50
param set CA_ROTOR6_CT +12.50
param set CA_ROTOR7_CT +12.50
param set CA_ROTOR4_KM -0.012
param set CA_ROTOR5_KM -0.012
param set CA_ROTOR6_KM +0.012
param set CA_ROTOR7_KM +0.012

# frame geometry (right-side-up)
param set CA_ROTOR0_PX +0.092
param set CA_ROTOR1_PX -0.092
param set CA_ROTOR2_PX +0.092
param set CA_ROTOR3_PX -0.092
param set CA_ROTOR0_PY +0.092
param set CA_ROTOR1_PY -0.092
param set CA_ROTOR2_PY -0.092
param set CA_ROTOR3_PY +0.092
param set CA_ROTOR0_PZ +0.010
param set CA_ROTOR1_PZ +0.010
param set CA_ROTOR2_PZ +0.010
param set CA_ROTOR3_PZ +0.010
param set CA_ROTOR0_AX +0.000
param set CA_ROTOR1_AX -0.000
param set CA_ROTOR2_AX +0.000
param set CA_ROTOR3_AX -0.000
param set CA_ROTOR0_AY +0.000
param set CA_ROTOR1_AY -0.000
param set CA_ROTOR2_AY -0.000
param set CA_ROTOR3_AY +0.000
param set CA_ROTOR0_AZ -1.000
param set CA_ROTOR1_AZ -1.000
param set CA_ROTOR2_AZ -1.000
param set CA_ROTOR3_AZ -1.000
# frame geometry (up-side-down)
param set CA_ROTOR4_PX +0.117
param set CA_ROTOR5_PX -0.117
param set CA_ROTOR6_PX +0.117
param set CA_ROTOR7_PX -0.117
param set CA_ROTOR4_PY +0.038
param set CA_ROTOR5_PY -0.038
param set CA_ROTOR6_PY -0.038
param set CA_ROTOR7_PY +0.038
param set CA_ROTOR4_PZ +0.010
param set CA_ROTOR5_PZ +0.010
param set CA_ROTOR6_PZ +0.010
param set CA_ROTOR7_PZ +0.010
param set CA_ROTOR4_AX +0.000
param set CA_ROTOR5_AX -0.000
param set CA_ROTOR6_AX +0.000
param set CA_ROTOR7_AX -0.000
param set CA_ROTOR4_AY +0.842
param set CA_ROTOR5_AY -0.842
param set CA_ROTOR6_AY -0.842
param set CA_ROTOR7_AY +0.842
param set CA_ROTOR4_AZ -0.540
param set CA_ROTOR5_AZ -0.540
param set CA_ROTOR6_AZ -0.540
param set CA_ROTOR7_AZ -0.540
